/* Create Policies */
INSERT INTO PRICE_POLICY (ID, POLICY_TYPE, FEE, HOUR_PRICE) VALUES(1,  'Fee', 5.0, 10.0);
INSERT INTO PRICE_POLICY (ID, POLICY_TYPE, FEE, HOUR_PRICE) VALUES( 2, 'NoFee', 0.0, 10.0);

/* Create Owner */
INSERT INTO CAR_SLOT_OWNER (ID, NAME , PRICE_POLICY_ID ) VALUES(1, 'Good Company', 2);
INSERT INTO CAR_SLOT_OWNER  (ID, NAME , PRICE_POLICY_ID ) VALUES(2,'Bad Company', 1);

/* Create Car slot types */
INSERT INTO CAR_SLOT_TYPE (ID ,TYPE_NAME ) VALUES (1, 'Gasoline');
INSERT INTO CAR_SLOT_TYPE (ID ,TYPE_NAME ) VALUES (2, 'Low Powered electrical');
INSERT INTO CAR_SLOT_TYPE (ID ,TYPE_NAME ) VALUES (3, 'High Powered electrical');
INSERT INTO CAR_SLOT_TYPE (ID ,TYPE_NAME ) VALUES (4, 'typeNoFreeSlot');

/* Create Car slots */
INSERT INTO CAR_SLOT (SLOT_NUMBER ,OWNER_ID, SLOT_TYPE_ID) VALUES (1, 1, 1);
INSERT INTO CAR_SLOT (SLOT_NUMBER ,OWNER_ID, SLOT_TYPE_ID) VALUES (2, 1, 2);
INSERT INTO CAR_SLOT (SLOT_NUMBER ,OWNER_ID, SLOT_TYPE_ID) VALUES (3, 1, 3);
INSERT INTO CAR_SLOT (SLOT_NUMBER ,OWNER_ID, SLOT_TYPE_ID) VALUES (4, 2, 1);
INSERT INTO CAR_SLOT (SLOT_NUMBER ,OWNER_ID, SLOT_TYPE_ID) VALUES (5, 2, 2);
INSERT INTO CAR_SLOT (SLOT_NUMBER ,OWNER_ID, SLOT_TYPE_ID) VALUES (6, 2, 3);
